# Default attributes for ut2k4 server cookbook
default[:ut2k4][:server][:dir] = 'server'
default[:ut2k4][:server][:web] = '/var/www/ut2k4_public'
default[:ut2k4][:server][:service_user] = 'ut2k4'
default[:ut2k4][:server][:name] = 'UT2K4 Server'
default[:ut2k4][:server][:short_name] = 'UT2k4 Server'
default[:ut2k4][:server][:motd] = 'Welcome to the Server!'
default[:ut2k4][:server][:password] = ''
default[:ut2k4][:server][:port] = '7777'
default[:ut2k4][:server][:cdkey] = 'SERIAL_HERE'
default[:ut2k4][:server][:region] = '0'
default[:ut2k4][:server][:admin][:name] = 'admin'
default[:ut2k4][:server][:admin][:email] = ''
default[:ut2k4][:server][:admin][:password] = 'admin'
default[:ut2k4][:server][:password] = ''
default[:ut2k4][:server][:default_map] = 'CTF-BridgeOfFate'
default[:ut2k4][:server][:default_type] = 'XGame.xCTFGame'